Smalltalk current createPackage: 'Easnoth-Rendering'!
CWImageLeaf subclass: #CWBackground
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWBackground subclass: #CWOverTile
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWOverTile subclass: #CWGameOverTile
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWBackground subclass: #CWTile
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWNode subclass: #CWCell
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWNode subclass: #CWMap
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

CWImageLeaf subclass: #CWMonster
	instanceVariableNames: ''
	package: 'Easnoth-Rendering'!

