Smalltalk current createPackage: 'Easnoth-Tests' properties: #{}!
TestCase subclass: #EasnothTest
	instanceVariableNames: ''
	package: 'Easnoth-Tests'!

EasnothTest subclass: #CellTest
	instanceVariableNames: ''
	package: 'Easnoth-Tests'!

EasnothTest subclass: #MapTest
	instanceVariableNames: ''
	package: 'Easnoth-Tests'!

EasnothTest subclass: #TileTest
	instanceVariableNames: ''
	package: 'Easnoth-Tests'!

